### ISSUE TITLE
Particles only in first view

### ISSUE THREAD

**Issue by lancekrogers** [SwapBlocks/website_2.0#5]
Add particles to all white backgrounds

**Comment by Ethannnrogers** [comment]
Can't get the particles to display in more than one area. Idk what the difference between the particles library I used and the Particles.js library, but the one I am using does not have very many capabilities.

**Comment by Ethannnrogers** [comment]
need to do testing for the responsiveness of the particles. Might need to only have particles on screens wider than 1200px.

**Comment by lancekrogers** [comment]
Did you try having multiple canvases?

**Comment by Ethannnrogers** [comment]
Yes. I am pretty sure the library I am using is only made for one display. All of the examples have it being used only on login pages on websites.

**Comment by lancekrogers** [comment]
Hmm ok I guess we'll have to look into something else

**Comment by lancekrogers** [comment]
Particles only need to be in the first view
