### ISSUE TITLE
Update content

### ISSUE THREAD

**Issue by lancekrogers** [SwapBlocks/website_2.0#7]
The swapblocks protocol reduces the role of middlemen to advisory/underwriting roles and liquidity providers. 

Remove --Anyone can act as a market maker. --

Completed & existing orders in any market are viewable by buyers & sellers, removing informational asymmetry. No trusted intermediary required.

**Comment by lancekrogers** [comment]
Update ---Stock splits, proxy voting, P&I payments & dividends can be fully or partially automated. Central securities depositories can be disintermediated.

---cant remember what needed to be updated, ignore for now

**Comment by lancekrogers** [comment]
Participants can retain custody of their assets. Decentralized trading removes the need for 

***Remove -- brokers and -- ***

central securities depositories to hold your assets. Settlement is instant and fully automated.

**Comment by Ethannnrogers** [comment]
> The swapblocks protocol reduces the role of middlemen to advisory/underwriting roles and liquidity providers.
> 
> Remove --Anyone can act as a market maker. --
> 
> Completed & existing orders in any market are viewable by buyers & sellers, removing informational asymmetry. No trusted intermediary required.


Wait so I just remove that 'Anyone can act as a market maker.' and don't replace it with anything?

**Comment by lancekrogers** [comment]
Yes
